### ISSUE TITLE
Exchange smart contract

### ISSUE THREAD

**Issue by jijordre** [hubiinetwork/striim-contracts#6]
### Description
Implement _Exchange_ smart contract according to section [Exchange in specification (v0.12)](https://docs.google.com/document/d/1-bsvatGLP89FNUccg6oxGQQEFgYAyBfIiNDeknyklJM/edit#heading=h.4b2biutfxjco).

The Exchange smart contract is the orchestrator of trades and payments on-chain including a.o. settlements and challenges.

### Implementation subissues
* Generic
  * [x] Import from abandoned DexTrade contract (#21)
* Continuous challenges
  * [x] Challenge fraudulent deal by trade (#14)
  * [x] Challenge fraudulent deal by payment (#15)
  * [x] Challenge fraudulent deal by balance (#16)
  * [x] Challenge fraudulent deal by trade order residual (#17)
  * [x] Challenge double spent order (#18)
* Deal settlement
  * [x] Settle deal (#19)
* (Remainder to be gauged later)

### Definition of done
* Implementation of all subissues done

### Depends on
* Client fund (#3)
* Community vote (#7)
* Revenue fund (#8)
* Reserve fund (#4)
* Community vote (#7)
* Security bond (#10)
* Configuration (#5)
